// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yiwckubajmlhnsjqsham.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlpd2NrdWJham1saG5zanFzaGFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTM2MDAsImV4cCI6MjA2MzkyOTYwMH0.XAK1-agwtpVxcEZTYsrChVM9EM-jhiWRvUzmqhGUgpA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);